### ISSUE TITLE
Replace the motor phase connector with a cable inlet and bring the phase wires out

### ISSUE THREAD

**Issue by dimracer** [Zubax/Komar#23]

**Comment by dimracer** [comment]
@j3qq4hch how is it going?

**Comment by j3qq4hch** [comment]
![image](https://user-images.githubusercontent.com/9300016/111750753-aa69b300-88a4-11eb-9517-35eeaad4a9dc.png)
This thing is descrubed long ago. There was no point in opening this issue. Close it.
