### ISSUE TITLE
Change FET

### ISSUE THREAD

**Issue by suzonch** [Zubax/Komar#33]
Current one is obsolete, change the attribute

**Comment by suzonch** [comment]
Changed

**Comment by pavel-kirienko** [comment]
@suzonch changed where? Please link the changeset.

**Comment by suzonch** [comment]
here https://github.com/Zubax/Komar/pull/34/files

**Comment by pavel-kirienko** [comment]
Okay. Remember that issues can only be closed after the main branch is updated. You can automate this: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
