### ISSUE TITLE
Increase the hardware over-current protection trip level

### ISSUE THREAD

**Issue by suzonch** [Zubax/Komar#39]
Set hardware over-current protection trip level to >400A

**Comment by pavel-kirienko** [comment]
(at least)

**Comment by suzonch** [comment]
Setting R7 to 16K = 427A
@Zentrus  Please change value like myxa for R7 using this https://www.mouser.ee/ProductDetail/Panasonic/ERJ-PA2F1602X?qs=V%252BBODeGd91K%252BbnqeObzfJQ%3D%3D
