### ISSUE TITLE
Datasheet issues

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/Komar#4]
@j3qq4hch configure your text editor to do the following automatically:

- Strip trailing whitespaces on save.
- Insert a trailing newline at the end of the file automatically.
- Expand tabs to 4 spaces.

There are at least the following issues with the doc that are immediately apparent:

- `can_intergration.png` -- fix the typo and replace it with a vector image.
- "LED Indication" --> "LED indication"
- UART for board-level communication? You must have copy-pasted it from the Mitochondrik doc without reading it.
- Mitochondrik is a proper name hence it shall be capitalized.
- Sentences end with a full stop.

I did not look past the third page. Please finish your job and let us know when it's ready for review.

**Comment by clyde-johnston** [comment]
These issues have been addressed in the latest commit in the 'datasheet' branch.
