### ISSUE TITLE
Cosmetic upgrades

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/Komar#46]
- [x] Upgrade the Mitochondrik symbol in the schematics to match the datasheet
- [x] Make USB DNM
- [x] This sheet is not needed and is, in fact, obsolete:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/3298404/215155816-f9edd97a-9f22-4b6b-b58a-5962a6fecebb.png">

**Comment by abualkasim-bakeer** [comment]
Are there any other requirements for this issue @Zentrus ?

**Comment by Zentrus** [comment]
I believe nothing else is required for this.
