### ISSUE TITLE
LED indicators

### ISSUE THREAD

**Issue by clyde-johnston** [Zubax/Komar#6]
There is no diagram dedicated to showing the location of all the LEDs.  Instead, they are shown in Figure 3.1 alongside communication interfaces and in Figure 4.1.  Some of the LEDs shown in the figures are not described (e.g. GATE ENABLE LED, Status RGB LED and Communication LED), and the Inverter enabled LED is described but not shown.

**Comment by j3qq4hch** [comment]
Ok, I fixed it in 752a7f45245c540a391adefc60ef2606be8336ec
