### ISSUE TITLE
Обновление корпуса

### ISSUE THREAD

**Issue by j3qq4hch** [Zubax/Komar#7]
![image](https://user-images.githubusercontent.com/9300016/81064779-f86f0580-8ee2-11ea-81c7-4bca2695cc02.png)
В текущей версии корпуса предполагается монтировать устройство при помощи четырех винтов М3, которые должны вкручиваться в глухие отверстия глубиной 3.8 мм на дне корпуса. 
Сечение это части выглядит вот так:
![image](https://user-images.githubusercontent.com/9300016/81065578-6405a280-8ee4-11ea-8e9b-8cbef4547ae6.png)

Выбор размера крепежных отверстий обусловлен общей компактностью устройства и увеличить их не представляется возможным без значительных модификаций всего корпуса.

Главная проблема в том, что в глухих отверстиях невозможно нарезать резьбу на всю глубину отверстия. В нашем же случае глубина так невелика, что производителю удалось нарезать совсем немного витков. 

Я не нашел однозначного ответа для этого конкретного случая, однако, сочетание малого количества витков, малого диаметра крепежа а также сравнительно низкой прочности материала не вселяют уверенности в надежность такого соединения. 

Вариантов решения этой проблемы я вижу только два:
1) Значительная переработка корпуса
2) Замена глухих отверстий на сквозные, что позволит нарезать резьбу на всю длину отверстия.

**Comment by j3qq4hch** [comment]
![image](https://user-images.githubusercontent.com/9300016/81077476-b4393080-8ef5-11ea-95f6-69933c49b6ac.png)
Вот что получается, если сделать отверстия сквозными. Выглядит крайне сомнительно

**Comment by j3qq4hch** [comment]
Вот так его можно починить, не увеличивая минимальный необходимый диаметр фрезы
![image](https://user-images.githubusercontent.com/9300016/81177091-ca56f780-8fae-11ea-9108-44613b869c05.png)

**Comment by j3qq4hch** [comment]
модель доступна здесь https://a360.co/3cak0cZ

**Comment by dimracer** [comment]
Я, пожалуй, вставлю сюда немного расчетов. 
Как известно, нагрузка среди витков резьбы распределяется неравномерно. 
![image](https://user-images.githubusercontent.com/11502518/81484961-7b30f100-9252-11ea-8d38-f75286ec715d.png)
Примерно 99% нагрузки приходится на первые 6 витков. Поэтому использовать более длинную резьбу в данном случае будет нецелесообразно. 
Шаг резьбы М4 равен 0.7 мм. 
Значит, длина резьбы должна быть 0.7 х 6 = 4.2 мм.

**Comment by dimracer** [comment]
По результатам обсуждения на созвоне приняты следующие изменения:
* Опытно-расчётным путем установлено, что при толщине стенки 1 мм (как сейчас), происходит деформация верхней крышки корпуса уже при нагрузке 14 кг (минимальная номинальная нагрузка). А должен быть запас как минимум 5-6 кг. Поэтому необходимо увеличить толщину всех стенок до 2 мм.
* Монтажные отверстия в нижней крышке можно сделать сквозными, т.к. это значительно упростит производство и обеспечит необходимую длину резьбы.

**Comment by pavel-kirienko** [comment]
Нельзя ли уменьшить шаг оребрения нижней части с целью увеличения площади поверхности (уменьшения теплового сопротивления корпус-среда) и уменьшения массы?

<img width="86" alt="image" src="https://user-images.githubusercontent.com/3298404/81605319-f40e8500-93d9-11ea-8dbd-239f4c15f2b9.png">

**Comment by j3qq4hch** [comment]
Самая последня актуальная версия корпуса доступна [здесь](https://a360.co/3gHx3Wd)

**Comment by dimracer** [comment]
Я все, конечно, понимаю. Вы заботитесь об удобстве. Но вот этот разъем питания ни чуть не добавляет удобства. А выглядит просто ужасно. Уберите его. 
![image](https://user-images.githubusercontent.com/11502518/83871127-2a6cc500-a738-11ea-8a5f-17871f3b203a.png)

**Comment by j3qq4hch** [comment]
Нажмите правой кнопкой на нем, там будет пункт "скрыть"

**Comment by dimracer** [comment]
Я понимаю, просто пользователям такое показывать нельзя. Пожалуйста, уберите этот кронштейн.

**Comment by dimracer** [comment]
Почему во Fusion проект имеет название 'Zubax Komar v40'? Пожалуйста, исправьте на v0.3.
Какие еще есть изменения, кроме описанных в [Readme](https://github.com/Zubax/Komar/tree/V-0.3)?

**Comment by j3qq4hch** [comment]
не обращайте внимания на V40, это версионирование внутри Fusion. Все значимые изменения описаны в readme.

**Comment by dimracer** [comment]
Раз уж у нас нет исходников корпуса в репозитории, а есть ссылка на вот эту модель во Fusion, то эта модель приравнивается к исходнику репозитория. А значит, версия релиза должна соответствовать версии корпуса во Fusion. В дальнейшем, как я уже говорил, конечно хотелось бы чтобы все было в репозитории. Иначе отследить изменения будет просто невозможно.

**Comment by j3qq4hch** [comment]
Готово. Корпус лежит в репозитории, ссылка больше не работает

**Comment by j3qq4hch** [comment]
К этому сообщению прикреплены три пояснительных документа, которые нужно отправлять производителю корпуса вместе с моделями на всякий случай. 

[bottom.pdf](https://github.com/Zubax/Komar/files/4736710/bottom.pdf)
[dummy.pdf](https://github.com/Zubax/Komar/files/4736711/dummy.pdf)
[top.pdf](https://github.com/Zubax/Komar/files/4736712/top.pdf)
